/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as SplashscreenIndexRouteImport } from './routes/splashscreen/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainErrorTestRouteImport } from './routes/_main/error-test'
import { Route as SplashscreenCrashIndexRouteImport } from './routes/splashscreen/crash/index'
import { Route as PublicAuthIndexRouteImport } from './routes/public/auth/index'
import { Route as MainSettingsIndexRouteImport } from './routes/_main/settings/index'
import { Route as MainSearchIndexRouteImport } from './routes/_main/search/index'
import { Route as MainOfflineIndexRouteImport } from './routes/_main/offline/index'
import { Route as MainMediastreamIndexRouteImport } from './routes/_main/mediastream/index'
import { Route as MainMedialinksIndexRouteImport } from './routes/_main/medialinks/index'
import { Route as MainExtensionsIndexRouteImport } from './routes/_main/extensions/index'
import { Route as MainEntryIndexRouteImport } from './routes/_main/entry/index'
import { Route as MainDiscoverIndexRouteImport } from './routes/_main/discover/index'
import { Route as MainCustomSourcesIndexRouteImport } from './routes/_main/custom-sources/index'
import { Route as MainReadingEntryIndexRouteImport } from './routes/_main/reading/entry/index'
import { Route as MainAuthCallbackIndexRouteImport } from './routes/_main/auth/callback/index'
import { Route as MainOfflineEntryReadingIndexRouteImport } from './routes/_main/offline/entry/reading/index'
import { Route as MainOfflineEntryMediaIndexRouteImport } from './routes/_main/offline/entry/media/index'

const ScanLogViewerIndexLazyRouteImport = createFileRoute('/scan-log-viewer/')()
const IssueReportIndexLazyRouteImport = createFileRoute('/issue-report/')()
const DocsIndexLazyRouteImport = createFileRoute('/docs/')()
const MainWebviewIndexLazyRouteImport = createFileRoute('/_main/webview/')()
const MainTorrentListIndexLazyRouteImport = createFileRoute(
  '/_main/torrent-list/',
)()
const MainSyncIndexLazyRouteImport = createFileRoute('/_main/sync/')()
const MainScheduleIndexLazyRouteImport = createFileRoute('/_main/schedule/')()
const MainScanSummariesIndexLazyRouteImport = createFileRoute(
  '/_main/scan-summaries/',
)()
const MainReadingIndexLazyRouteImport = createFileRoute('/_main/reading/')()
const MainQbittorrentIndexLazyRouteImport = createFileRoute(
  '/_main/qbittorrent/',
)()
const MainListsIndexLazyRouteImport = createFileRoute('/_main/lists/')()
const MainDebridIndexLazyRouteImport = createFileRoute('/_main/debrid/')()
const MainAutoDownloaderIndexLazyRouteImport = createFileRoute(
  '/_main/auto-downloader/',
)()
const MainOfflineReadingIndexLazyRouteImport = createFileRoute(
  '/_main/offline/reading/',
)()
const MainExtensionsPlaygroundIndexLazyRouteImport = createFileRoute(
  '/_main/extensions/playground/',
)()

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanLogViewerIndexLazyRoute = ScanLogViewerIndexLazyRouteImport.update({
  id: '/scan-log-viewer/',
  path: '/scan-log-viewer/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/scan-log-viewer/index.lazy').then((d) => d.Route),
)
const IssueReportIndexLazyRoute = IssueReportIndexLazyRouteImport.update({
  id: '/issue-report/',
  path: '/issue-report/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/issue-report/index.lazy').then((d) => d.Route),
)
const DocsIndexLazyRoute = DocsIndexLazyRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/docs/index.lazy').then((d) => d.Route))
const SplashscreenIndexRoute = SplashscreenIndexRouteImport.update({
  id: '/splashscreen/',
  path: '/splashscreen/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainErrorTestRoute = MainErrorTestRouteImport.update({
  id: '/error-test',
  path: '/error-test',
  getParentRoute: () => MainRoute,
} as any)
const MainWebviewIndexLazyRoute = MainWebviewIndexLazyRouteImport.update({
  id: '/webview/',
  path: '/webview/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/webview/index.lazy').then((d) => d.Route),
)
const MainTorrentListIndexLazyRoute =
  MainTorrentListIndexLazyRouteImport.update({
    id: '/torrent-list/',
    path: '/torrent-list/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/torrent-list/index.lazy').then((d) => d.Route),
  )
const MainSyncIndexLazyRoute = MainSyncIndexLazyRouteImport.update({
  id: '/sync/',
  path: '/sync/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/sync/index.lazy').then((d) => d.Route),
)
const MainScheduleIndexLazyRoute = MainScheduleIndexLazyRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/schedule/index.lazy').then((d) => d.Route),
)
const MainScanSummariesIndexLazyRoute =
  MainScanSummariesIndexLazyRouteImport.update({
    id: '/scan-summaries/',
    path: '/scan-summaries/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/scan-summaries/index.lazy').then((d) => d.Route),
  )
const MainReadingIndexLazyRoute = MainReadingIndexLazyRouteImport.update({
  id: '/reading/',
  path: '/reading/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/reading/index.lazy').then((d) => d.Route),
)
const MainQbittorrentIndexLazyRoute =
  MainQbittorrentIndexLazyRouteImport.update({
    id: '/qbittorrent/',
    path: '/qbittorrent/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/qbittorrent/index.lazy').then((d) => d.Route),
  )
const MainListsIndexLazyRoute = MainListsIndexLazyRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/lists/index.lazy').then((d) => d.Route),
)
const MainDebridIndexLazyRoute = MainDebridIndexLazyRouteImport.update({
  id: '/debrid/',
  path: '/debrid/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/debrid/index.lazy').then((d) => d.Route),
)
const MainAutoDownloaderIndexLazyRoute =
  MainAutoDownloaderIndexLazyRouteImport.update({
    id: '/auto-downloader/',
    path: '/auto-downloader/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/auto-downloader/index.lazy').then((d) => d.Route),
  )
const SplashscreenCrashIndexRoute = SplashscreenCrashIndexRouteImport.update({
  id: '/splashscreen/crash/',
  path: '/splashscreen/crash/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthIndexRoute = PublicAuthIndexRouteImport.update({
  id: '/public/auth/',
  path: '/public/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainSettingsIndexRoute = MainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/settings/index.lazy').then((d) => d.Route),
)
const MainSearchIndexRoute = MainSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/search/index.lazy').then((d) => d.Route),
)
const MainOfflineIndexRoute = MainOfflineIndexRouteImport.update({
  id: '/offline/',
  path: '/offline/',
  getParentRoute: () => MainRoute,
} as any)
const MainMediastreamIndexRoute = MainMediastreamIndexRouteImport.update({
  id: '/mediastream/',
  path: '/mediastream/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/mediastream/index.lazy').then((d) => d.Route),
)
const MainMedialinksIndexRoute = MainMedialinksIndexRouteImport.update({
  id: '/medialinks/',
  path: '/medialinks/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/medialinks/index.lazy').then((d) => d.Route),
)
const MainExtensionsIndexRoute = MainExtensionsIndexRouteImport.update({
  id: '/extensions/',
  path: '/extensions/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/extensions/index.lazy').then((d) => d.Route),
)
const MainEntryIndexRoute = MainEntryIndexRouteImport.update({
  id: '/entry/',
  path: '/entry/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/entry/index.lazy').then((d) => d.Route),
)
const MainDiscoverIndexRoute = MainDiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/discover/index.lazy').then((d) => d.Route),
)
const MainCustomSourcesIndexRoute = MainCustomSourcesIndexRouteImport.update({
  id: '/custom-sources/',
  path: '/custom-sources/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/custom-sources/index.lazy').then((d) => d.Route),
)
const MainOfflineReadingIndexLazyRoute =
  MainOfflineReadingIndexLazyRouteImport.update({
    id: '/offline/reading/',
    path: '/offline/reading/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/offline/reading/index.lazy').then((d) => d.Route),
  )
const MainExtensionsPlaygroundIndexLazyRoute =
  MainExtensionsPlaygroundIndexLazyRouteImport.update({
    id: '/extensions/playground/',
    path: '/extensions/playground/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/extensions/playground/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainReadingEntryIndexRoute = MainReadingEntryIndexRouteImport.update({
  id: '/reading/entry/',
  path: '/reading/entry/',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/reading/entry/index.lazy').then((d) => d.Route),
)
const MainAuthCallbackIndexRoute = MainAuthCallbackIndexRouteImport.update({
  id: '/auth/callback/',
  path: '/auth/callback/',
  getParentRoute: () => MainRoute,
} as any)
const MainOfflineEntryReadingIndexRoute =
  MainOfflineEntryReadingIndexRouteImport.update({
    id: '/offline/entry/reading/',
    path: '/offline/entry/reading/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/offline/entry/reading/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MainOfflineEntryMediaIndexRoute =
  MainOfflineEntryMediaIndexRouteImport.update({
    id: '/offline/entry/media/',
    path: '/offline/entry/media/',
    getParentRoute: () => MainRoute,
  } as any).lazy(() =>
    import('./routes/_main/offline/entry/media/index.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/error-test': typeof MainErrorTestRoute
  '/splashscreen/': typeof SplashscreenIndexRoute
  '/docs/': typeof DocsIndexLazyRoute
  '/issue-report/': typeof IssueReportIndexLazyRoute
  '/scan-log-viewer/': typeof ScanLogViewerIndexLazyRoute
  '/custom-sources/': typeof MainCustomSourcesIndexRoute
  '/discover/': typeof MainDiscoverIndexRoute
  '/entry/': typeof MainEntryIndexRoute
  '/extensions/': typeof MainExtensionsIndexRoute
  '/medialinks/': typeof MainMedialinksIndexRoute
  '/mediastream/': typeof MainMediastreamIndexRoute
  '/offline/': typeof MainOfflineIndexRoute
  '/search/': typeof MainSearchIndexRoute
  '/settings/': typeof MainSettingsIndexRoute
  '/public/auth/': typeof PublicAuthIndexRoute
  '/splashscreen/crash/': typeof SplashscreenCrashIndexRoute
  '/auto-downloader/': typeof MainAutoDownloaderIndexLazyRoute
  '/debrid/': typeof MainDebridIndexLazyRoute
  '/lists/': typeof MainListsIndexLazyRoute
  '/qbittorrent/': typeof MainQbittorrentIndexLazyRoute
  '/reading/': typeof MainReadingIndexLazyRoute
  '/scan-summaries/': typeof MainScanSummariesIndexLazyRoute
  '/schedule/': typeof MainScheduleIndexLazyRoute
  '/sync/': typeof MainSyncIndexLazyRoute
  '/torrent-list/': typeof MainTorrentListIndexLazyRoute
  '/webview/': typeof MainWebviewIndexLazyRoute
  '/auth/callback/': typeof MainAuthCallbackIndexRoute
  '/reading/entry/': typeof MainReadingEntryIndexRoute
  '/extensions/playground/': typeof MainExtensionsPlaygroundIndexLazyRoute
  '/offline/reading/': typeof MainOfflineReadingIndexLazyRoute
  '/offline/entry/media/': typeof MainOfflineEntryMediaIndexRoute
  '/offline/entry/reading/': typeof MainOfflineEntryReadingIndexRoute
}
export interface FileRoutesByTo {
  '/error-test': typeof MainErrorTestRoute
  '/': typeof MainIndexRoute
  '/splashscreen': typeof SplashscreenIndexRoute
  '/docs': typeof DocsIndexLazyRoute
  '/issue-report': typeof IssueReportIndexLazyRoute
  '/scan-log-viewer': typeof ScanLogViewerIndexLazyRoute
  '/custom-sources': typeof MainCustomSourcesIndexRoute
  '/discover': typeof MainDiscoverIndexRoute
  '/entry': typeof MainEntryIndexRoute
  '/extensions': typeof MainExtensionsIndexRoute
  '/medialinks': typeof MainMedialinksIndexRoute
  '/mediastream': typeof MainMediastreamIndexRoute
  '/offline': typeof MainOfflineIndexRoute
  '/search': typeof MainSearchIndexRoute
  '/settings': typeof MainSettingsIndexRoute
  '/public/auth': typeof PublicAuthIndexRoute
  '/splashscreen/crash': typeof SplashscreenCrashIndexRoute
  '/auto-downloader': typeof MainAutoDownloaderIndexLazyRoute
  '/debrid': typeof MainDebridIndexLazyRoute
  '/lists': typeof MainListsIndexLazyRoute
  '/qbittorrent': typeof MainQbittorrentIndexLazyRoute
  '/reading': typeof MainReadingIndexLazyRoute
  '/scan-summaries': typeof MainScanSummariesIndexLazyRoute
  '/schedule': typeof MainScheduleIndexLazyRoute
  '/sync': typeof MainSyncIndexLazyRoute
  '/torrent-list': typeof MainTorrentListIndexLazyRoute
  '/webview': typeof MainWebviewIndexLazyRoute
  '/auth/callback': typeof MainAuthCallbackIndexRoute
  '/reading/entry': typeof MainReadingEntryIndexRoute
  '/extensions/playground': typeof MainExtensionsPlaygroundIndexLazyRoute
  '/offline/reading': typeof MainOfflineReadingIndexLazyRoute
  '/offline/entry/media': typeof MainOfflineEntryMediaIndexRoute
  '/offline/entry/reading': typeof MainOfflineEntryReadingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/error-test': typeof MainErrorTestRoute
  '/_main/': typeof MainIndexRoute
  '/splashscreen/': typeof SplashscreenIndexRoute
  '/docs/': typeof DocsIndexLazyRoute
  '/issue-report/': typeof IssueReportIndexLazyRoute
  '/scan-log-viewer/': typeof ScanLogViewerIndexLazyRoute
  '/_main/custom-sources/': typeof MainCustomSourcesIndexRoute
  '/_main/discover/': typeof MainDiscoverIndexRoute
  '/_main/entry/': typeof MainEntryIndexRoute
  '/_main/extensions/': typeof MainExtensionsIndexRoute
  '/_main/medialinks/': typeof MainMedialinksIndexRoute
  '/_main/mediastream/': typeof MainMediastreamIndexRoute
  '/_main/offline/': typeof MainOfflineIndexRoute
  '/_main/search/': typeof MainSearchIndexRoute
  '/_main/settings/': typeof MainSettingsIndexRoute
  '/public/auth/': typeof PublicAuthIndexRoute
  '/splashscreen/crash/': typeof SplashscreenCrashIndexRoute
  '/_main/auto-downloader/': typeof MainAutoDownloaderIndexLazyRoute
  '/_main/debrid/': typeof MainDebridIndexLazyRoute
  '/_main/lists/': typeof MainListsIndexLazyRoute
  '/_main/qbittorrent/': typeof MainQbittorrentIndexLazyRoute
  '/_main/reading/': typeof MainReadingIndexLazyRoute
  '/_main/scan-summaries/': typeof MainScanSummariesIndexLazyRoute
  '/_main/schedule/': typeof MainScheduleIndexLazyRoute
  '/_main/sync/': typeof MainSyncIndexLazyRoute
  '/_main/torrent-list/': typeof MainTorrentListIndexLazyRoute
  '/_main/webview/': typeof MainWebviewIndexLazyRoute
  '/_main/auth/callback/': typeof MainAuthCallbackIndexRoute
  '/_main/reading/entry/': typeof MainReadingEntryIndexRoute
  '/_main/extensions/playground/': typeof MainExtensionsPlaygroundIndexLazyRoute
  '/_main/offline/reading/': typeof MainOfflineReadingIndexLazyRoute
  '/_main/offline/entry/media/': typeof MainOfflineEntryMediaIndexRoute
  '/_main/offline/entry/reading/': typeof MainOfflineEntryReadingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error-test'
    | '/splashscreen/'
    | '/docs/'
    | '/issue-report/'
    | '/scan-log-viewer/'
    | '/custom-sources/'
    | '/discover/'
    | '/entry/'
    | '/extensions/'
    | '/medialinks/'
    | '/mediastream/'
    | '/offline/'
    | '/search/'
    | '/settings/'
    | '/public/auth/'
    | '/splashscreen/crash/'
    | '/auto-downloader/'
    | '/debrid/'
    | '/lists/'
    | '/qbittorrent/'
    | '/reading/'
    | '/scan-summaries/'
    | '/schedule/'
    | '/sync/'
    | '/torrent-list/'
    | '/webview/'
    | '/auth/callback/'
    | '/reading/entry/'
    | '/extensions/playground/'
    | '/offline/reading/'
    | '/offline/entry/media/'
    | '/offline/entry/reading/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error-test'
    | '/'
    | '/splashscreen'
    | '/docs'
    | '/issue-report'
    | '/scan-log-viewer'
    | '/custom-sources'
    | '/discover'
    | '/entry'
    | '/extensions'
    | '/medialinks'
    | '/mediastream'
    | '/offline'
    | '/search'
    | '/settings'
    | '/public/auth'
    | '/splashscreen/crash'
    | '/auto-downloader'
    | '/debrid'
    | '/lists'
    | '/qbittorrent'
    | '/reading'
    | '/scan-summaries'
    | '/schedule'
    | '/sync'
    | '/torrent-list'
    | '/webview'
    | '/auth/callback'
    | '/reading/entry'
    | '/extensions/playground'
    | '/offline/reading'
    | '/offline/entry/media'
    | '/offline/entry/reading'
  id:
    | '__root__'
    | '/_main'
    | '/_main/error-test'
    | '/_main/'
    | '/splashscreen/'
    | '/docs/'
    | '/issue-report/'
    | '/scan-log-viewer/'
    | '/_main/custom-sources/'
    | '/_main/discover/'
    | '/_main/entry/'
    | '/_main/extensions/'
    | '/_main/medialinks/'
    | '/_main/mediastream/'
    | '/_main/offline/'
    | '/_main/search/'
    | '/_main/settings/'
    | '/public/auth/'
    | '/splashscreen/crash/'
    | '/_main/auto-downloader/'
    | '/_main/debrid/'
    | '/_main/lists/'
    | '/_main/qbittorrent/'
    | '/_main/reading/'
    | '/_main/scan-summaries/'
    | '/_main/schedule/'
    | '/_main/sync/'
    | '/_main/torrent-list/'
    | '/_main/webview/'
    | '/_main/auth/callback/'
    | '/_main/reading/entry/'
    | '/_main/extensions/playground/'
    | '/_main/offline/reading/'
    | '/_main/offline/entry/media/'
    | '/_main/offline/entry/reading/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  SplashscreenIndexRoute: typeof SplashscreenIndexRoute
  DocsIndexLazyRoute: typeof DocsIndexLazyRoute
  IssueReportIndexLazyRoute: typeof IssueReportIndexLazyRoute
  ScanLogViewerIndexLazyRoute: typeof ScanLogViewerIndexLazyRoute
  PublicAuthIndexRoute: typeof PublicAuthIndexRoute
  SplashscreenCrashIndexRoute: typeof SplashscreenCrashIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-log-viewer/': {
      id: '/scan-log-viewer/'
      path: '/scan-log-viewer'
      fullPath: '/scan-log-viewer/'
      preLoaderRoute: typeof ScanLogViewerIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue-report/': {
      id: '/issue-report/'
      path: '/issue-report'
      fullPath: '/issue-report/'
      preLoaderRoute: typeof IssueReportIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splashscreen/': {
      id: '/splashscreen/'
      path: '/splashscreen'
      fullPath: '/splashscreen/'
      preLoaderRoute: typeof SplashscreenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/error-test': {
      id: '/_main/error-test'
      path: '/error-test'
      fullPath: '/error-test'
      preLoaderRoute: typeof MainErrorTestRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/webview/': {
      id: '/_main/webview/'
      path: '/webview'
      fullPath: '/webview/'
      preLoaderRoute: typeof MainWebviewIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/torrent-list/': {
      id: '/_main/torrent-list/'
      path: '/torrent-list'
      fullPath: '/torrent-list/'
      preLoaderRoute: typeof MainTorrentListIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/sync/': {
      id: '/_main/sync/'
      path: '/sync'
      fullPath: '/sync/'
      preLoaderRoute: typeof MainSyncIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/schedule/': {
      id: '/_main/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof MainScheduleIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/scan-summaries/': {
      id: '/_main/scan-summaries/'
      path: '/scan-summaries'
      fullPath: '/scan-summaries/'
      preLoaderRoute: typeof MainScanSummariesIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/reading/': {
      id: '/_main/reading/'
      path: '/reading'
      fullPath: '/reading/'
      preLoaderRoute: typeof MainReadingIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/qbittorrent/': {
      id: '/_main/qbittorrent/'
      path: '/qbittorrent'
      fullPath: '/qbittorrent/'
      preLoaderRoute: typeof MainQbittorrentIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/lists/': {
      id: '/_main/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof MainListsIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/debrid/': {
      id: '/_main/debrid/'
      path: '/debrid'
      fullPath: '/debrid/'
      preLoaderRoute: typeof MainDebridIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/auto-downloader/': {
      id: '/_main/auto-downloader/'
      path: '/auto-downloader'
      fullPath: '/auto-downloader/'
      preLoaderRoute: typeof MainAutoDownloaderIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/splashscreen/crash/': {
      id: '/splashscreen/crash/'
      path: '/splashscreen/crash'
      fullPath: '/splashscreen/crash/'
      preLoaderRoute: typeof SplashscreenCrashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/auth/': {
      id: '/public/auth/'
      path: '/public/auth'
      fullPath: '/public/auth/'
      preLoaderRoute: typeof PublicAuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/settings/': {
      id: '/_main/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof MainSettingsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/search/': {
      id: '/_main/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof MainSearchIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/offline/': {
      id: '/_main/offline/'
      path: '/offline'
      fullPath: '/offline/'
      preLoaderRoute: typeof MainOfflineIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/mediastream/': {
      id: '/_main/mediastream/'
      path: '/mediastream'
      fullPath: '/mediastream/'
      preLoaderRoute: typeof MainMediastreamIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/medialinks/': {
      id: '/_main/medialinks/'
      path: '/medialinks'
      fullPath: '/medialinks/'
      preLoaderRoute: typeof MainMedialinksIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/extensions/': {
      id: '/_main/extensions/'
      path: '/extensions'
      fullPath: '/extensions/'
      preLoaderRoute: typeof MainExtensionsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/entry/': {
      id: '/_main/entry/'
      path: '/entry'
      fullPath: '/entry/'
      preLoaderRoute: typeof MainEntryIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/discover/': {
      id: '/_main/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof MainDiscoverIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/custom-sources/': {
      id: '/_main/custom-sources/'
      path: '/custom-sources'
      fullPath: '/custom-sources/'
      preLoaderRoute: typeof MainCustomSourcesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/offline/reading/': {
      id: '/_main/offline/reading/'
      path: '/offline/reading'
      fullPath: '/offline/reading/'
      preLoaderRoute: typeof MainOfflineReadingIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/extensions/playground/': {
      id: '/_main/extensions/playground/'
      path: '/extensions/playground'
      fullPath: '/extensions/playground/'
      preLoaderRoute: typeof MainExtensionsPlaygroundIndexLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/reading/entry/': {
      id: '/_main/reading/entry/'
      path: '/reading/entry'
      fullPath: '/reading/entry/'
      preLoaderRoute: typeof MainReadingEntryIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/auth/callback/': {
      id: '/_main/auth/callback/'
      path: '/auth/callback'
      fullPath: '/auth/callback/'
      preLoaderRoute: typeof MainAuthCallbackIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/offline/entry/reading/': {
      id: '/_main/offline/entry/reading/'
      path: '/offline/entry/reading'
      fullPath: '/offline/entry/reading/'
      preLoaderRoute: typeof MainOfflineEntryReadingIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/offline/entry/media/': {
      id: '/_main/offline/entry/media/'
      path: '/offline/entry/media'
      fullPath: '/offline/entry/media/'
      preLoaderRoute: typeof MainOfflineEntryMediaIndexRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainErrorTestRoute: typeof MainErrorTestRoute
  MainIndexRoute: typeof MainIndexRoute
  MainCustomSourcesIndexRoute: typeof MainCustomSourcesIndexRoute
  MainDiscoverIndexRoute: typeof MainDiscoverIndexRoute
  MainEntryIndexRoute: typeof MainEntryIndexRoute
  MainExtensionsIndexRoute: typeof MainExtensionsIndexRoute
  MainMedialinksIndexRoute: typeof MainMedialinksIndexRoute
  MainMediastreamIndexRoute: typeof MainMediastreamIndexRoute
  MainOfflineIndexRoute: typeof MainOfflineIndexRoute
  MainSearchIndexRoute: typeof MainSearchIndexRoute
  MainSettingsIndexRoute: typeof MainSettingsIndexRoute
  MainAutoDownloaderIndexLazyRoute: typeof MainAutoDownloaderIndexLazyRoute
  MainDebridIndexLazyRoute: typeof MainDebridIndexLazyRoute
  MainListsIndexLazyRoute: typeof MainListsIndexLazyRoute
  MainQbittorrentIndexLazyRoute: typeof MainQbittorrentIndexLazyRoute
  MainReadingIndexLazyRoute: typeof MainReadingIndexLazyRoute
  MainScanSummariesIndexLazyRoute: typeof MainScanSummariesIndexLazyRoute
  MainScheduleIndexLazyRoute: typeof MainScheduleIndexLazyRoute
  MainSyncIndexLazyRoute: typeof MainSyncIndexLazyRoute
  MainTorrentListIndexLazyRoute: typeof MainTorrentListIndexLazyRoute
  MainWebviewIndexLazyRoute: typeof MainWebviewIndexLazyRoute
  MainAuthCallbackIndexRoute: typeof MainAuthCallbackIndexRoute
  MainReadingEntryIndexRoute: typeof MainReadingEntryIndexRoute
  MainExtensionsPlaygroundIndexLazyRoute: typeof MainExtensionsPlaygroundIndexLazyRoute
  MainOfflineReadingIndexLazyRoute: typeof MainOfflineReadingIndexLazyRoute
  MainOfflineEntryMediaIndexRoute: typeof MainOfflineEntryMediaIndexRoute
  MainOfflineEntryReadingIndexRoute: typeof MainOfflineEntryReadingIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainErrorTestRoute: MainErrorTestRoute,
  MainIndexRoute: MainIndexRoute,
  MainCustomSourcesIndexRoute: MainCustomSourcesIndexRoute,
  MainDiscoverIndexRoute: MainDiscoverIndexRoute,
  MainEntryIndexRoute: MainEntryIndexRoute,
  MainExtensionsIndexRoute: MainExtensionsIndexRoute,
  MainMedialinksIndexRoute: MainMedialinksIndexRoute,
  MainMediastreamIndexRoute: MainMediastreamIndexRoute,
  MainOfflineIndexRoute: MainOfflineIndexRoute,
  MainSearchIndexRoute: MainSearchIndexRoute,
  MainSettingsIndexRoute: MainSettingsIndexRoute,
  MainAutoDownloaderIndexLazyRoute: MainAutoDownloaderIndexLazyRoute,
  MainDebridIndexLazyRoute: MainDebridIndexLazyRoute,
  MainListsIndexLazyRoute: MainListsIndexLazyRoute,
  MainQbittorrentIndexLazyRoute: MainQbittorrentIndexLazyRoute,
  MainReadingIndexLazyRoute: MainReadingIndexLazyRoute,
  MainScanSummariesIndexLazyRoute: MainScanSummariesIndexLazyRoute,
  MainScheduleIndexLazyRoute: MainScheduleIndexLazyRoute,
  MainSyncIndexLazyRoute: MainSyncIndexLazyRoute,
  MainTorrentListIndexLazyRoute: MainTorrentListIndexLazyRoute,
  MainWebviewIndexLazyRoute: MainWebviewIndexLazyRoute,
  MainAuthCallbackIndexRoute: MainAuthCallbackIndexRoute,
  MainReadingEntryIndexRoute: MainReadingEntryIndexRoute,
  MainExtensionsPlaygroundIndexLazyRoute:
    MainExtensionsPlaygroundIndexLazyRoute,
  MainOfflineReadingIndexLazyRoute: MainOfflineReadingIndexLazyRoute,
  MainOfflineEntryMediaIndexRoute: MainOfflineEntryMediaIndexRoute,
  MainOfflineEntryReadingIndexRoute: MainOfflineEntryReadingIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  SplashscreenIndexRoute: SplashscreenIndexRoute,
  DocsIndexLazyRoute: DocsIndexLazyRoute,
  IssueReportIndexLazyRoute: IssueReportIndexLazyRoute,
  ScanLogViewerIndexLazyRoute: ScanLogViewerIndexLazyRoute,
  PublicAuthIndexRoute: PublicAuthIndexRoute,
  SplashscreenCrashIndexRoute: SplashscreenCrashIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
