export const SIMKL_DISCOVER_GENRES = [
    "Action",
    "Adventure",
    "Animation",
    "Biography",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Family",
    "Fantasy",
    "History",
    "Horror",
    "Kids",
    "Martial Arts",
    "Mecha",
    "Music",
    "Mystery",
    "Reality",
    "Romance",
    "School",
    "Sci-Fi",
    "Slice of Life",
    "Sports",
    "Supernatural",
    "Talk Show",
    "Thriller",
    "War",
    "Western",
]
