export const SIMKL_DISCOVER_GENRES = [
    "Action",
    "Adventure",
    "Animation",
    "Biography",
    "Children",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Ecchi",
    "Family",
    "Fantasy",
    "Food",
    "Gag Humor",
    "Gore",
    "Harem",
    "History",
    "Horror",
    "Isekai",
    "Josei",
    "Kids",
    "Magic",
    "Martial Arts",
    "Mecha",
    "Military",
    "Music",
    "Musical",
    "Mystery",
    "Parody",
    "Psychological",
    "Racing",
    "Reality",
    "Reincarnation",
    "Romance",
    "Samurai",
    "School",
    "Sci-Fi",
    "Seinen",
    "Shoujo",
    "Shounen",
    "Slice of Life",
    "Space",
    "Sports",
    "Super Power",
    "Supernatural",
    "Talk Show",
    "Thriller",
    "Vampire",
    "War",
    "Western",
]
